<?php

use Illuminate\Database\Seeder;

class RegenciesTableSeeder extends Seeder
{
    private function _getData()
    {
        return [
            ['id_city' => 1101, 'province_id' => 11, 'name' => "KABUPATEN SIMEULUE",],
            ['id_city' => 1102, 'province_id' => 11, 'name' => "KABUPATEN ACEH SINGKIL",],
            ['id_city' => 1103, 'province_id' => 11, 'name' => "KABUPATEN ACEH SELATAN",],
            ['id_city' => 1104, 'province_id' => 11, 'name' => "KABUPATEN ACEH TENGGARA",],
            ['id_city' => 1105, 'province_id' => 11, 'name' => "KABUPATEN ACEH TIMUR",],
            ['id_city' => 1106, 'province_id' => 11, 'name' => "KABUPATEN ACEH TENGAH",],
            ['id_city' => 1107, 'province_id' => 11, 'name' => "KABUPATEN ACEH BARAT",],
            ['id_city' => 1108, 'province_id' => 11, 'name' => "KABUPATEN ACEH BESAR",],
            ['id_city' => 1109, 'province_id' => 11, 'name' => "KABUPATEN PIDIE",],
            ['id_city' => 1110, 'province_id' => 11, 'name' => "KABUPATEN BIREUEN",],
            ['id_city' => 1111, 'province_id' => 11, 'name' => "KABUPATEN ACEH UTARA",],
            ['id_city' => 1112, 'province_id' => 11, 'name' => "KABUPATEN ACEH BARAT DAYA",],
            ['id_city' => 1113, 'province_id' => 11, 'name' => "KABUPATEN GAYO LUES",],
            ['id_city' => 1114, 'province_id' => 11, 'name' => "KABUPATEN ACEH TAMIANG",],
            ['id_city' => 1115, 'province_id' => 11, 'name' => "KABUPATEN NAGAN RAYA",],
            ['id_city' => 1116, 'province_id' => 11, 'name' => "KABUPATEN ACEH JAYA",],
            ['id_city' => 1117, 'province_id' => 11, 'name' => "KABUPATEN BENER MERIAH",],
            ['id_city' => 1118, 'province_id' => 11, 'name' => "KABUPATEN PIDIE JAYA",],
            ['id_city' => 1171, 'province_id' => 11, 'name' => "KOTA BANDA ACEH",],
            ['id_city' => 1172, 'province_id' => 11, 'name' => "KOTA SABANG",],
            ['id_city' => 1173, 'province_id' => 11, 'name' => "KOTA LANGSA",],
            ['id_city' => 1174, 'province_id' => 11, 'name' => "KOTA LHOKSEUMAWE",],
            ['id_city' => 1175, 'province_id' => 11, 'name' => "KOTA SUBULUSSALAM",],
            ['id_city' => 1201, 'province_id' => 12, 'name' => "KABUPATEN NIAS",],
            ['id_city' => 1202, 'province_id' => 12, 'name' => "KABUPATEN MANDAILING NATAL",],
            ['id_city' => 1203, 'province_id' => 12, 'name' => "KABUPATEN TAPANULI SELATAN",],
            ['id_city' => 1204, 'province_id' => 12, 'name' => "KABUPATEN TAPANULI TENGAH",],
            ['id_city' => 1205, 'province_id' => 12, 'name' => "KABUPATEN TAPANULI UTARA",],
            ['id_city' => 1206, 'province_id' => 12, 'name' => "KABUPATEN TOBA SAMOSIR",],
            ['id_city' => 1207, 'province_id' => 12, 'name' => "KABUPATEN LABUHAN BATU",],
            ['id_city' => 1208, 'province_id' => 12, 'name' => "KABUPATEN ASAHAN",],
            ['id_city' => 1209, 'province_id' => 12, 'name' => "KABUPATEN SIMALUNGUN",],
            ['id_city' => 1210, 'province_id' => 12, 'name' => "KABUPATEN DAIRI",],
            ['id_city' => 1211, 'province_id' => 12, 'name' => "KABUPATEN KARO",],
            ['id_city' => 1212, 'province_id' => 12, 'name' => "KABUPATEN DELI SERDANG",],
            ['id_city' => 1213, 'province_id' => 12, 'name' => "KABUPATEN LANGKAT",],
            ['id_city' => 1214, 'province_id' => 12, 'name' => "KABUPATEN NIAS SELATAN",],
            ['id_city' => 1215, 'province_id' => 12, 'name' => "KABUPATEN HUMBANG HASUNDUTAN",],
            ['id_city' => 1216, 'province_id' => 12, 'name' => "KABUPATEN PAKPAK BHARAT",],
            ['id_city' => 1217, 'province_id' => 12, 'name' => "KABUPATEN SAMOSIR",],
            ['id_city' => 1218, 'province_id' => 12, 'name' => "KABUPATEN SERDANG BEDAGAI",],
            ['id_city' => 1219, 'province_id' => 12, 'name' => "KABUPATEN BATU BARA",],
            ['id_city' => 1220, 'province_id' => 12, 'name' => "KABUPATEN PADANG LAWAS UTARA",],
            ['id_city' => 1221, 'province_id' => 12, 'name' => "KABUPATEN PADANG LAWAS",],
            ['id_city' => 1222, 'province_id' => 12, 'name' => "KABUPATEN LABUHAN BATU SELATAN",],
            ['id_city' => 1223, 'province_id' => 12, 'name' => "KABUPATEN LABUHAN BATU UTARA",],
            ['id_city' => 1224, 'province_id' => 12, 'name' => "KABUPATEN NIAS UTARA",],
            ['id_city' => 1225, 'province_id' => 12, 'name' => "KABUPATEN NIAS BARAT",],
            ['id_city' => 1271, 'province_id' => 12, 'name' => "KOTA SIBOLGA",],
            ['id_city' => 1272, 'province_id' => 12, 'name' => "KOTA TANJUNG BALAI",],
            ['id_city' => 1273, 'province_id' => 12, 'name' => "KOTA PEMATANG SIANTAR",],
            ['id_city' => 1274, 'province_id' => 12, 'name' => "KOTA TEBING TINGGI",],
            ['id_city' => 1275, 'province_id' => 12, 'name' => "KOTA MEDAN",],
            ['id_city' => 1276, 'province_id' => 12, 'name' => "KOTA BINJAI",],
            ['id_city' => 1277, 'province_id' => 12, 'name' => "KOTA PADANGSIDIMPUAN",],
            ['id_city' => 1278, 'province_id' => 12, 'name' => "KOTA GUNUNGSITOLI",],
            ['id_city' => 1301, 'province_id' => 13, 'name' => "KABUPATEN KEPULAUAN MENTAWAI",],
            ['id_city' => 1302, 'province_id' => 13, 'name' => "KABUPATEN PESISIR SELATAN",],
            ['id_city' => 1303, 'province_id' => 13, 'name' => "KABUPATEN SOLOK",],
            ['id_city' => 1304, 'province_id' => 13, 'name' => "KABUPATEN SIJUNJUNG",],
            ['id_city' => 1305, 'province_id' => 13, 'name' => "KABUPATEN TANAH DATAR",],
            ['id_city' => 1306, 'province_id' => 13, 'name' => "KABUPATEN PADANG PARIAMAN",],
            ['id_city' => 1307, 'province_id' => 13, 'name' => "KABUPATEN AGAM",],
            ['id_city' => 1308, 'province_id' => 13, 'name' => "KABUPATEN LIMA PULUH KOTA",],
            ['id_city' => 1309, 'province_id' => 13, 'name' => "KABUPATEN PASAMAN",],
            ['id_city' => 1310, 'province_id' => 13, 'name' => "KABUPATEN SOLOK SELATAN",],
            ['id_city' => 1311, 'province_id' => 13, 'name' => "KABUPATEN DHARMASRAYA",],
            ['id_city' => 1312, 'province_id' => 13, 'name' => "KABUPATEN PASAMAN BARAT",],
            ['id_city' => 1371, 'province_id' => 13, 'name' => "KOTA PADANG",],
            ['id_city' => 1372, 'province_id' => 13, 'name' => "KOTA SOLOK",],
            ['id_city' => 1373, 'province_id' => 13, 'name' => "KOTA SAWAH LUNTO",],
            ['id_city' => 1374, 'province_id' => 13, 'name' => "KOTA PADANG PANJANG",],
            ['id_city' => 1375, 'province_id' => 13, 'name' => "KOTA BUKITTINGGI",],
            ['id_city' => 1376, 'province_id' => 13, 'name' => "KOTA PAYAKUMBUH",],
            ['id_city' => 1377, 'province_id' => 13, 'name' => "KOTA PARIAMAN",],
            ['id_city' => 1401, 'province_id' => 14, 'name' => "KABUPATEN KUANTAN SINGINGI",],
            ['id_city' => 1402, 'province_id' => 14, 'name' => "KABUPATEN INDRAGIRI HULU",],
            ['id_city' => 1403, 'province_id' => 14, 'name' => "KABUPATEN INDRAGIRI HILIR",],
            ['id_city' => 1404, 'province_id' => 14, 'name' => "KABUPATEN PELALAWAN",],
            ['id_city' => 1405, 'province_id' => 14, 'name' => "KABUPATEN S I A K",],
            ['id_city' => 1406, 'province_id' => 14, 'name' => "KABUPATEN KAMPAR",],
            ['id_city' => 1407, 'province_id' => 14, 'name' => "KABUPATEN ROKAN HULU",],
            ['id_city' => 1408, 'province_id' => 14, 'name' => "KABUPATEN BENGKALIS",],
            ['id_city' => 1409, 'province_id' => 14, 'name' => "KABUPATEN ROKAN HILIR",],
            ['id_city' => 1410, 'province_id' => 14, 'name' => "KABUPATEN KEPULAUAN MERANTI",],
            ['id_city' => 1471, 'province_id' => 14, 'name' => "KOTA PEKANBARU",],
            ['id_city' => 1473, 'province_id' => 14, 'name' => "KOTA D U M A I",],
            ['id_city' => 1501, 'province_id' => 15, 'name' => "KABUPATEN KERINCI",],
            ['id_city' => 1502, 'province_id' => 15, 'name' => "KABUPATEN MERANGIN",],
            ['id_city' => 1503, 'province_id' => 15, 'name' => "KABUPATEN SAROLANGUN",],
            ['id_city' => 1504, 'province_id' => 15, 'name' => "KABUPATEN BATANG HARI",],
            ['id_city' => 1505, 'province_id' => 15, 'name' => "KABUPATEN MUARO JAMBI",],
            ['id_city' => 1506, 'province_id' => 15, 'name' => "KABUPATEN TANJUNG JABUNG TIMUR",],
            ['id_city' => 1507, 'province_id' => 15, 'name' => "KABUPATEN TANJUNG JABUNG BARAT",],
            ['id_city' => 1508, 'province_id' => 15, 'name' => "KABUPATEN TEBO",],
            ['id_city' => 1509, 'province_id' => 15, 'name' => "KABUPATEN BUNGO",],
            ['id_city' => 1571, 'province_id' => 15, 'name' => "KOTA JAMBI",],
            ['id_city' => 1572, 'province_id' => 15, 'name' => "KOTA SUNGAI PENUH",],
            ['id_city' => 1601, 'province_id' => 16, 'name' => "KABUPATEN OGAN KOMERING ULU",],
            ['id_city' => 1602, 'province_id' => 16, 'name' => "KABUPATEN OGAN KOMERING ILIR",],
            ['id_city' => 1603, 'province_id' => 16, 'name' => "KABUPATEN MUARA ENIM",],
            ['id_city' => 1604, 'province_id' => 16, 'name' => "KABUPATEN LAHAT",],
            ['id_city' => 1605, 'province_id' => 16, 'name' => "KABUPATEN MUSI RAWAS",],
            ['id_city' => 1606, 'province_id' => 16, 'name' => "KABUPATEN MUSI BANYUASIN",],
            ['id_city' => 1607, 'province_id' => 16, 'name' => "KABUPATEN BANYU ASIN",],
            ['id_city' => 1608, 'province_id' => 16, 'name' => "KABUPATEN OGAN KOMERING ULU SELATAN",],
            ['id_city' => 1609, 'province_id' => 16, 'name' => "KABUPATEN OGAN KOMERING ULU TIMUR",],
            ['id_city' => 1610, 'province_id' => 16, 'name' => "KABUPATEN OGAN ILIR",],
            ['id_city' => 1611, 'province_id' => 16, 'name' => "KABUPATEN EMPAT LAWANG",],
            ['id_city' => 1612, 'province_id' => 16, 'name' => "KABUPATEN PENUKAL ABAB LEMATANG ILIR",],
            ['id_city' => 1613, 'province_id' => 16, 'name' => "KABUPATEN MUSI RAWAS UTARA",],
            ['id_city' => 1671, 'province_id' => 16, 'name' => "KOTA PALEMBANG",],
            ['id_city' => 1672, 'province_id' => 16, 'name' => "KOTA PRABUMULIH",],
            ['id_city' => 1673, 'province_id' => 16, 'name' => "KOTA PAGAR ALAM",],
            ['id_city' => 1674, 'province_id' => 16, 'name' => "KOTA LUBUKLINGGAU",],
            ['id_city' => 1701, 'province_id' => 17, 'name' => "KABUPATEN BENGKULU SELATAN",],
            ['id_city' => 1702, 'province_id' => 17, 'name' => "KABUPATEN REJANG LEBONG",],
            ['id_city' => 1703, 'province_id' => 17, 'name' => "KABUPATEN BENGKULU UTARA",],
            ['id_city' => 1704, 'province_id' => 17, 'name' => "KABUPATEN KAUR",],
            ['id_city' => 1705, 'province_id' => 17, 'name' => "KABUPATEN SELUMA",],
            ['id_city' => 1706, 'province_id' => 17, 'name' => "KABUPATEN MUKOMUKO",],
            ['id_city' => 1707, 'province_id' => 17, 'name' => "KABUPATEN LEBONG",],
            ['id_city' => 1708, 'province_id' => 17, 'name' => "KABUPATEN KEPAHIANG",],
            ['id_city' => 1709, 'province_id' => 17, 'name' => "KABUPATEN BENGKULU TENGAH",],
            ['id_city' => 1771, 'province_id' => 17, 'name' => "KOTA BENGKULU",],
            ['id_city' => 1801, 'province_id' => 18, 'name' => "KABUPATEN LAMPUNG BARAT",],
            ['id_city' => 1802, 'province_id' => 18, 'name' => "KABUPATEN TANGGAMUS",],
            ['id_city' => 1803, 'province_id' => 18, 'name' => "KABUPATEN LAMPUNG SELATAN",],
            ['id_city' => 1804, 'province_id' => 18, 'name' => "KABUPATEN LAMPUNG TIMUR",],
            ['id_city' => 1805, 'province_id' => 18, 'name' => "KABUPATEN LAMPUNG TENGAH",],
            ['id_city' => 1806, 'province_id' => 18, 'name' => "KABUPATEN LAMPUNG UTARA",],
            ['id_city' => 1807, 'province_id' => 18, 'name' => "KABUPATEN WAY KANAN",],
            ['id_city' => 1808, 'province_id' => 18, 'name' => "KABUPATEN TULANGBAWANG",],
            ['id_city' => 1809, 'province_id' => 18, 'name' => "KABUPATEN PESAWARAN",],
            ['id_city' => 1810, 'province_id' => 18, 'name' => "KABUPATEN PRINGSEWU",],
            ['id_city' => 1811, 'province_id' => 18, 'name' => "KABUPATEN MESUJI",],
            ['id_city' => 1812, 'province_id' => 18, 'name' => "KABUPATEN TULANG BAWANG BARAT",],
            ['id_city' => 1813, 'province_id' => 18, 'name' => "KABUPATEN PESISIR BARAT",],
            ['id_city' => 1871, 'province_id' => 18, 'name' => "KOTA BANDAR LAMPUNG",],
            ['id_city' => 1872, 'province_id' => 18, 'name' => "KOTA METRO",],
            ['id_city' => 1901, 'province_id' => 19, 'name' => "KABUPATEN BANGKA",],
            ['id_city' => 1902, 'province_id' => 19, 'name' => "KABUPATEN BELITUNG",],
            ['id_city' => 1903, 'province_id' => 19, 'name' => "KABUPATEN BANGKA BARAT",],
            ['id_city' => 1904, 'province_id' => 19, 'name' => "KABUPATEN BANGKA TENGAH",],
            ['id_city' => 1905, 'province_id' => 19, 'name' => "KABUPATEN BANGKA SELATAN",],
            ['id_city' => 1906, 'province_id' => 19, 'name' => "KABUPATEN BELITUNG TIMUR",],
            ['id_city' => 1971, 'province_id' => 19, 'name' => "KOTA PANGKAL PINANG",],
            ['id_city' => 2101, 'province_id' => 21, 'name' => "KABUPATEN KARIMUN",],
            ['id_city' => 2102, 'province_id' => 21, 'name' => "KABUPATEN BINTAN",],
            ['id_city' => 2103, 'province_id' => 21, 'name' => "KABUPATEN NATUNA",],
            ['id_city' => 2104, 'province_id' => 21, 'name' => "KABUPATEN LINGGA",],
            ['id_city' => 2105, 'province_id' => 21, 'name' => "KABUPATEN KEPULAUAN ANAMBAS",],
            ['id_city' => 2171, 'province_id' => 21, 'name' => "KOTA B A T A M",],
            ['id_city' => 2172, 'province_id' => 21, 'name' => "KOTA TANJUNG PINANG",],
            ['id_city' => 3101, 'province_id' => 31, 'name' => "KABUPATEN KEPULAUAN SERIBU",],
            ['id_city' => 3171, 'province_id' => 31, 'name' => "KOTA JAKARTA SELATAN",],
            ['id_city' => 3172, 'province_id' => 31, 'name' => "KOTA JAKARTA TIMUR",],
            ['id_city' => 3173, 'province_id' => 31, 'name' => "KOTA JAKARTA PUSAT",],
            ['id_city' => 3174, 'province_id' => 31, 'name' => "KOTA JAKARTA BARAT",],
            ['id_city' => 3175, 'province_id' => 31, 'name' => "KOTA JAKARTA UTARA",],
            ['id_city' => 3201, 'province_id' => 32, 'name' => "KABUPATEN BOGOR",],
            ['id_city' => 3202, 'province_id' => 32, 'name' => "KABUPATEN SUKABUMI",],
            ['id_city' => 3203, 'province_id' => 32, 'name' => "KABUPATEN CIANJUR",],
            ['id_city' => 3204, 'province_id' => 32, 'name' => "KABUPATEN BANDUNG",],
            ['id_city' => 3205, 'province_id' => 32, 'name' => "KABUPATEN GARUT",],
            ['id_city' => 3206, 'province_id' => 32, 'name' => "KABUPATEN TASIKMALAYA",],
            ['id_city' => 3207, 'province_id' => 32, 'name' => "KABUPATEN CIAMIS",],
            ['id_city' => 3208, 'province_id' => 32, 'name' => "KABUPATEN KUNINGAN",],
            ['id_city' => 3209, 'province_id' => 32, 'name' => "KABUPATEN CIREBON",],
            ['id_city' => 3210, 'province_id' => 32, 'name' => "KABUPATEN MAJALENGKA",],
            ['id_city' => 3211, 'province_id' => 32, 'name' => "KABUPATEN SUMEDANG",],
            ['id_city' => 3212, 'province_id' => 32, 'name' => "KABUPATEN INDRAMAYU",],
            ['id_city' => 3213, 'province_id' => 32, 'name' => "KABUPATEN SUBANG",],
            ['id_city' => 3214, 'province_id' => 32, 'name' => "KABUPATEN PURWAKARTA",],
            ['id_city' => 3215, 'province_id' => 32, 'name' => "KABUPATEN KARAWANG",],
            ['id_city' => 3216, 'province_id' => 32, 'name' => "KABUPATEN BEKASI",],
            ['id_city' => 3217, 'province_id' => 32, 'name' => "KABUPATEN BANDUNG BARAT",],
            ['id_city' => 3218, 'province_id' => 32, 'name' => "KABUPATEN PANGANDARAN",],
            ['id_city' => 3271, 'province_id' => 32, 'name' => "KOTA BOGOR",],
            ['id_city' => 3272, 'province_id' => 32, 'name' => "KOTA SUKABUMI",],
            ['id_city' => 3273, 'province_id' => 32, 'name' => "KOTA BANDUNG",],
            ['id_city' => 3274, 'province_id' => 32, 'name' => "KOTA CIREBON",],
            ['id_city' => 3275, 'province_id' => 32, 'name' => "KOTA BEKASI",],
            ['id_city' => 3276, 'province_id' => 32, 'name' => "KOTA DEPOK",],
            ['id_city' => 3277, 'province_id' => 32, 'name' => "KOTA CIMAHI",],
            ['id_city' => 3278, 'province_id' => 32, 'name' => "KOTA TASIKMALAYA",],
            ['id_city' => 3279, 'province_id' => 32, 'name' => "KOTA BANJAR",],
            ['id_city' => 3301, 'province_id' => 33, 'name' => "KABUPATEN CILACAP",],
            ['id_city' => 3302, 'province_id' => 33, 'name' => "KABUPATEN BANYUMAS",],
            ['id_city' => 3303, 'province_id' => 33, 'name' => "KABUPATEN PURBALINGGA",],
            ['id_city' => 3304, 'province_id' => 33, 'name' => "KABUPATEN BANJARNEGARA",],
            ['id_city' => 3305, 'province_id' => 33, 'name' => "KABUPATEN KEBUMEN",],
            ['id_city' => 3306, 'province_id' => 33, 'name' => "KABUPATEN PURWOREJO",],
            ['id_city' => 3307, 'province_id' => 33, 'name' => "KABUPATEN WONOSOBO",],
            ['id_city' => 3308, 'province_id' => 33, 'name' => "KABUPATEN MAGELANG",],
            ['id_city' => 3309, 'province_id' => 33, 'name' => "KABUPATEN BOYOLALI",],
            ['id_city' => 3310, 'province_id' => 33, 'name' => "KABUPATEN KLATEN",],
            ['id_city' => 3311, 'province_id' => 33, 'name' => "KABUPATEN SUKOHARJO",],
            ['id_city' => 3312, 'province_id' => 33, 'name' => "KABUPATEN WONOGIRI",],
            ['id_city' => 3313, 'province_id' => 33, 'name' => "KABUPATEN KARANGANYAR",],
            ['id_city' => 3314, 'province_id' => 33, 'name' => "KABUPATEN SRAGEN",],
            ['id_city' => 3315, 'province_id' => 33, 'name' => "KABUPATEN GROBOGAN",],
            ['id_city' => 3316, 'province_id' => 33, 'name' => "KABUPATEN BLORA",],
            ['id_city' => 3317, 'province_id' => 33, 'name' => "KABUPATEN REMBANG",],
            ['id_city' => 3318, 'province_id' => 33, 'name' => "KABUPATEN PATI",],
            ['id_city' => 3319, 'province_id' => 33, 'name' => "KABUPATEN KUDUS",],
            ['id_city' => 3320, 'province_id' => 33, 'name' => "KABUPATEN JEPARA",],
            ['id_city' => 3321, 'province_id' => 33, 'name' => "KABUPATEN DEMAK",],
            ['id_city' => 3322, 'province_id' => 33, 'name' => "KABUPATEN SEMARANG",],
            ['id_city' => 3323, 'province_id' => 33, 'name' => "KABUPATEN TEMANGGUNG",],
            ['id_city' => 3324, 'province_id' => 33, 'name' => "KABUPATEN KENDAL",],
            ['id_city' => 3325, 'province_id' => 33, 'name' => "KABUPATEN BATANG",],
            ['id_city' => 3326, 'province_id' => 33, 'name' => "KABUPATEN PEKALONGAN",],
            ['id_city' => 3327, 'province_id' => 33, 'name' => "KABUPATEN PEMALANG",],
            ['id_city' => 3328, 'province_id' => 33, 'name' => "KABUPATEN TEGAL",],
            ['id_city' => 3329, 'province_id' => 33, 'name' => "KABUPATEN BREBES",],
            ['id_city' => 3371, 'province_id' => 33, 'name' => "KOTA MAGELANG",],
            ['id_city' => 3372, 'province_id' => 33, 'name' => "KOTA SURAKARTA",],
            ['id_city' => 3373, 'province_id' => 33, 'name' => "KOTA SALATIGA",],
            ['id_city' => 3374, 'province_id' => 33, 'name' => "KOTA SEMARANG",],
            ['id_city' => 3375, 'province_id' => 33, 'name' => "KOTA PEKALONGAN",],
            ['id_city' => 3376, 'province_id' => 33, 'name' => "KOTA TEGAL",],
            ['id_city' => 3401, 'province_id' => 34, 'name' => "KABUPATEN KULON PROGO",],
            ['id_city' => 3402, 'province_id' => 34, 'name' => "KABUPATEN BANTUL",],
            ['id_city' => 3403, 'province_id' => 34, 'name' => "KABUPATEN GUNUNG KIDUL",],
            ['id_city' => 3404, 'province_id' => 34, 'name' => "KABUPATEN SLEMAN",],
            ['id_city' => 3471, 'province_id' => 34, 'name' => "KOTA YOGYAKARTA",],
            ['id_city' => 3501, 'province_id' => 35, 'name' => "KABUPATEN PACITAN",],
            ['id_city' => 3502, 'province_id' => 35, 'name' => "KABUPATEN PONOROGO",],
            ['id_city' => 3503, 'province_id' => 35, 'name' => "KABUPATEN TRENGGALEK",],
            ['id_city' => 3504, 'province_id' => 35, 'name' => "KABUPATEN TULUNGAGUNG",],
            ['id_city' => 3505, 'province_id' => 35, 'name' => "KABUPATEN BLITAR",],
            ['id_city' => 3506, 'province_id' => 35, 'name' => "KABUPATEN KEDIRI",],
            ['id_city' => 3507, 'province_id' => 35, 'name' => "KABUPATEN MALANG",],
            ['id_city' => 3508, 'province_id' => 35, 'name' => "KABUPATEN LUMAJANG",],
            ['id_city' => 3509, 'province_id' => 35, 'name' => "KABUPATEN JEMBER",],
            ['id_city' => 3510, 'province_id' => 35, 'name' => "KABUPATEN BANYUWANGI",],
            ['id_city' => 3511, 'province_id' => 35, 'name' => "KABUPATEN BONDOWOSO",],
            ['id_city' => 3512, 'province_id' => 35, 'name' => "KABUPATEN SITUBONDO",],
            ['id_city' => 3513, 'province_id' => 35, 'name' => "KABUPATEN PROBOLINGGO",],
            ['id_city' => 3514, 'province_id' => 35, 'name' => "KABUPATEN PASURUAN",],
            ['id_city' => 3515, 'province_id' => 35, 'name' => "KABUPATEN SIDOARJO",],
            ['id_city' => 3516, 'province_id' => 35, 'name' => "KABUPATEN MOJOKERTO",],
            ['id_city' => 3517, 'province_id' => 35, 'name' => "KABUPATEN JOMBANG",],
            ['id_city' => 3518, 'province_id' => 35, 'name' => "KABUPATEN NGANJUK",],
            ['id_city' => 3519, 'province_id' => 35, 'name' => "KABUPATEN MADIUN",],
            ['id_city' => 3520, 'province_id' => 35, 'name' => "KABUPATEN MAGETAN",],
            ['id_city' => 3521, 'province_id' => 35, 'name' => "KABUPATEN NGAWI",],
            ['id_city' => 3522, 'province_id' => 35, 'name' => "KABUPATEN BOJONEGORO",],
            ['id_city' => 3523, 'province_id' => 35, 'name' => "KABUPATEN TUBAN",],
            ['id_city' => 3524, 'province_id' => 35, 'name' => "KABUPATEN LAMONGAN",],
            ['id_city' => 3525, 'province_id' => 35, 'name' => "KABUPATEN GRESIK",],
            ['id_city' => 3526, 'province_id' => 35, 'name' => "KABUPATEN BANGKALAN",],
            ['id_city' => 3527, 'province_id' => 35, 'name' => "KABUPATEN SAMPANG",],
            ['id_city' => 3528, 'province_id' => 35, 'name' => "KABUPATEN PAMEKASAN",],
            ['id_city' => 3529, 'province_id' => 35, 'name' => "KABUPATEN SUMENEP",],
            ['id_city' => 3571, 'province_id' => 35, 'name' => "KOTA KEDIRI",],
            ['id_city' => 3572, 'province_id' => 35, 'name' => "KOTA BLITAR",],
            ['id_city' => 3573, 'province_id' => 35, 'name' => "KOTA MALANG",],
            ['id_city' => 3574, 'province_id' => 35, 'name' => "KOTA PROBOLINGGO",],
            ['id_city' => 3575, 'province_id' => 35, 'name' => "KOTA PASURUAN",],
            ['id_city' => 3576, 'province_id' => 35, 'name' => "KOTA MOJOKERTO",],
            ['id_city' => 3577, 'province_id' => 35, 'name' => "KOTA MADIUN",],
            ['id_city' => 3578, 'province_id' => 35, 'name' => "KOTA SURABAYA",],
            ['id_city' => 3579, 'province_id' => 35, 'name' => "KOTA BATU",],
            ['id_city' => 3601, 'province_id' => 36, 'name' => "KABUPATEN PANDEGLANG",],
            ['id_city' => 3602, 'province_id' => 36, 'name' => "KABUPATEN LEBAK",],
            ['id_city' => 3603, 'province_id' => 36, 'name' => "KABUPATEN TANGERANG",],
            ['id_city' => 3604, 'province_id' => 36, 'name' => "KABUPATEN SERANG",],
            ['id_city' => 3671, 'province_id' => 36, 'name' => "KOTA TANGERANG",],
            ['id_city' => 3672, 'province_id' => 36, 'name' => "KOTA CILEGON",],
            ['id_city' => 3673, 'province_id' => 36, 'name' => "KOTA SERANG",],
            ['id_city' => 3674, 'province_id' => 36, 'name' => "KOTA TANGERANG SELATAN",],
            ['id_city' => 5101, 'province_id' => 51, 'name' => "KABUPATEN JEMBRANA",],
            ['id_city' => 5102, 'province_id' => 51, 'name' => "KABUPATEN TABANAN",],
            ['id_city' => 5103, 'province_id' => 51, 'name' => "KABUPATEN BADUNG",],
            ['id_city' => 5104, 'province_id' => 51, 'name' => "KABUPATEN GIANYAR",],
            ['id_city' => 5105, 'province_id' => 51, 'name' => "KABUPATEN KLUNGKUNG",],
            ['id_city' => 5106, 'province_id' => 51, 'name' => "KABUPATEN BANGLI",],
            ['id_city' => 5107, 'province_id' => 51, 'name' => "KABUPATEN KARANG ASEM",],
            ['id_city' => 5108, 'province_id' => 51, 'name' => "KABUPATEN BULELENG",],
            ['id_city' => 5171, 'province_id' => 51, 'name' => "KOTA DENPASAR",],
            ['id_city' => 5201, 'province_id' => 52, 'name' => "KABUPATEN LOMBOK BARAT",],
            ['id_city' => 5202, 'province_id' => 52, 'name' => "KABUPATEN LOMBOK TENGAH",],
            ['id_city' => 5203, 'province_id' => 52, 'name' => "KABUPATEN LOMBOK TIMUR",],
            ['id_city' => 5204, 'province_id' => 52, 'name' => "KABUPATEN SUMBAWA",],
            ['id_city' => 5205, 'province_id' => 52, 'name' => "KABUPATEN DOMPU",],
            ['id_city' => 5206, 'province_id' => 52, 'name' => "KABUPATEN BIMA",],
            ['id_city' => 5207, 'province_id' => 52, 'name' => "KABUPATEN SUMBAWA BARAT",],
            ['id_city' => 5208, 'province_id' => 52, 'name' => "KABUPATEN LOMBOK UTARA",],
            ['id_city' => 5271, 'province_id' => 52, 'name' => "KOTA MATARAM",],
            ['id_city' => 5272, 'province_id' => 52, 'name' => "KOTA BIMA",],
            ['id_city' => 5301, 'province_id' => 53, 'name' => "KABUPATEN SUMBA BARAT",],
            ['id_city' => 5302, 'province_id' => 53, 'name' => "KABUPATEN SUMBA TIMUR",],
            ['id_city' => 5303, 'province_id' => 53, 'name' => "KABUPATEN KUPANG",],
            ['id_city' => 5304, 'province_id' => 53, 'name' => "KABUPATEN TIMOR TENGAH SELATAN",],
            ['id_city' => 5305, 'province_id' => 53, 'name' => "KABUPATEN TIMOR TENGAH UTARA",],
            ['id_city' => 5306, 'province_id' => 53, 'name' => "KABUPATEN BELU",],
            ['id_city' => 5307, 'province_id' => 53, 'name' => "KABUPATEN ALOR",],
            ['id_city' => 5308, 'province_id' => 53, 'name' => "KABUPATEN LEMBATA",],
            ['id_city' => 5309, 'province_id' => 53, 'name' => "KABUPATEN FLORES TIMUR",],
            ['id_city' => 5310, 'province_id' => 53, 'name' => "KABUPATEN SIKKA",],
            ['id_city' => 5311, 'province_id' => 53, 'name' => "KABUPATEN ENDE",],
            ['id_city' => 5312, 'province_id' => 53, 'name' => "KABUPATEN NGADA",],
            ['id_city' => 5313, 'province_id' => 53, 'name' => "KABUPATEN MANGGARAI",],
            ['id_city' => 5314, 'province_id' => 53, 'name' => "KABUPATEN ROTE NDAO",],
            ['id_city' => 5315, 'province_id' => 53, 'name' => "KABUPATEN MANGGARAI BARAT",],
            ['id_city' => 5316, 'province_id' => 53, 'name' => "KABUPATEN SUMBA TENGAH",],
            ['id_city' => 5317, 'province_id' => 53, 'name' => "KABUPATEN SUMBA BARAT DAYA",],
            ['id_city' => 5318, 'province_id' => 53, 'name' => "KABUPATEN NAGEKEO",],
            ['id_city' => 5319, 'province_id' => 53, 'name' => "KABUPATEN MANGGARAI TIMUR",],
            ['id_city' => 5320, 'province_id' => 53, 'name' => "KABUPATEN SABU RAIJUA",],
            ['id_city' => 5321, 'province_id' => 53, 'name' => "KABUPATEN MALAKA",],
            ['id_city' => 5371, 'province_id' => 53, 'name' => "KOTA KUPANG",],
            ['id_city' => 6101, 'province_id' => 61, 'name' => "KABUPATEN SAMBAS",],
            ['id_city' => 6102, 'province_id' => 61, 'name' => "KABUPATEN BENGKAYANG",],
            ['id_city' => 6103, 'province_id' => 61, 'name' => "KABUPATEN LANDAK",],
            ['id_city' => 6104, 'province_id' => 61, 'name' => "KABUPATEN MEMPAWAH",],
            ['id_city' => 6105, 'province_id' => 61, 'name' => "KABUPATEN SANGGAU",],
            ['id_city' => 6106, 'province_id' => 61, 'name' => "KABUPATEN KETAPANG",],
            ['id_city' => 6107, 'province_id' => 61, 'name' => "KABUPATEN SINTANG",],
            ['id_city' => 6108, 'province_id' => 61, 'name' => "KABUPATEN KAPUAS HULU",],
            ['id_city' => 6109, 'province_id' => 61, 'name' => "KABUPATEN SEKADAU",],
            ['id_city' => 6110, 'province_id' => 61, 'name' => "KABUPATEN MELAWI",],
            ['id_city' => 6111, 'province_id' => 61, 'name' => "KABUPATEN KAYONG UTARA",],
            ['id_city' => 6112, 'province_id' => 61, 'name' => "KABUPATEN KUBU RAYA",],
            ['id_city' => 6171, 'province_id' => 61, 'name' => "KOTA PONTIANAK",],
            ['id_city' => 6172, 'province_id' => 61, 'name' => "KOTA SINGKAWANG",],
            ['id_city' => 6201, 'province_id' => 62, 'name' => "KABUPATEN KOTAWARINGIN BARAT",],
            ['id_city' => 6202, 'province_id' => 62, 'name' => "KABUPATEN KOTAWARINGIN TIMUR",],
            ['id_city' => 6203, 'province_id' => 62, 'name' => "KABUPATEN KAPUAS",],
            ['id_city' => 6204, 'province_id' => 62, 'name' => "KABUPATEN BARITO SELATAN",],
            ['id_city' => 6205, 'province_id' => 62, 'name' => "KABUPATEN BARITO UTARA",],
            ['id_city' => 6206, 'province_id' => 62, 'name' => "KABUPATEN SUKAMARA",],
            ['id_city' => 6207, 'province_id' => 62, 'name' => "KABUPATEN LAMANDAU",],
            ['id_city' => 6208, 'province_id' => 62, 'name' => "KABUPATEN SERUYAN",],
            ['id_city' => 6209, 'province_id' => 62, 'name' => "KABUPATEN KATINGAN",],
            ['id_city' => 6210, 'province_id' => 62, 'name' => "KABUPATEN PULANG PISAU",],
            ['id_city' => 6211, 'province_id' => 62, 'name' => "KABUPATEN GUNUNG MAS",],
            ['id_city' => 6212, 'province_id' => 62, 'name' => "KABUPATEN BARITO TIMUR",],
            ['id_city' => 6213, 'province_id' => 62, 'name' => "KABUPATEN MURUNG RAYA",],
            ['id_city' => 6271, 'province_id' => 62, 'name' => "KOTA PALANGKA RAYA",],
            ['id_city' => 6301, 'province_id' => 63, 'name' => "KABUPATEN TANAH LAUT",],
            ['id_city' => 6302, 'province_id' => 63, 'name' => "KABUPATEN KOTA BARU",],
            ['id_city' => 6303, 'province_id' => 63, 'name' => "KABUPATEN BANJAR",],
            ['id_city' => 6304, 'province_id' => 63, 'name' => "KABUPATEN BARITO KUALA",],
            ['id_city' => 6305, 'province_id' => 63, 'name' => "KABUPATEN TAPIN",],
            ['id_city' => 6306, 'province_id' => 63, 'name' => "KABUPATEN HULU SUNGAI SELATAN",],
            ['id_city' => 6307, 'province_id' => 63, 'name' => "KABUPATEN HULU SUNGAI TENGAH",],
            ['id_city' => 6308, 'province_id' => 63, 'name' => "KABUPATEN HULU SUNGAI UTARA",],
            ['id_city' => 6309, 'province_id' => 63, 'name' => "KABUPATEN TABALONG",],
            ['id_city' => 6310, 'province_id' => 63, 'name' => "KABUPATEN TANAH BUMBU",],
            ['id_city' => 6311, 'province_id' => 63, 'name' => "KABUPATEN BALANGAN",],
            ['id_city' => 6371, 'province_id' => 63, 'name' => "KOTA BANJARMASIN",],
            ['id_city' => 6372, 'province_id' => 63, 'name' => "KOTA BANJAR BARU",],
            ['id_city' => 6401, 'province_id' => 64, 'name' => "KABUPATEN PASER",],
            ['id_city' => 6402, 'province_id' => 64, 'name' => "KABUPATEN KUTAI BARAT",],
            ['id_city' => 6403, 'province_id' => 64, 'name' => "KABUPATEN KUTAI KARTANEGARA",],
            ['id_city' => 6404, 'province_id' => 64, 'name' => "KABUPATEN KUTAI TIMUR",],
            ['id_city' => 6405, 'province_id' => 64, 'name' => "KABUPATEN BERAU",],
            ['id_city' => 6409, 'province_id' => 64, 'name' => "KABUPATEN PENAJAM PASER UTARA",],
            ['id_city' => 6411, 'province_id' => 64, 'name' => "KABUPATEN MAHAKAM HULU",],
            ['id_city' => 6471, 'province_id' => 64, 'name' => "KOTA BALIKPAPAN",],
            ['id_city' => 6472, 'province_id' => 64, 'name' => "KOTA SAMARINDA",],
            ['id_city' => 6474, 'province_id' => 64, 'name' => "KOTA BONTANG",],
            ['id_city' => 6501, 'province_id' => 65, 'name' => "KABUPATEN MALINAU",],
            ['id_city' => 6502, 'province_id' => 65, 'name' => "KABUPATEN BULUNGAN",],
            ['id_city' => 6503, 'province_id' => 65, 'name' => "KABUPATEN TANA TIDUNG",],
            ['id_city' => 6504, 'province_id' => 65, 'name' => "KABUPATEN NUNUKAN",],
            ['id_city' => 6571, 'province_id' => 65, 'name' => "KOTA TARAKAN",],
            ['id_city' => 7101, 'province_id' => 71, 'name' => "KABUPATEN BOLAANG MONGONDOW",],
            ['id_city' => 7102, 'province_id' => 71, 'name' => "KABUPATEN MINAHASA",],
            ['id_city' => 7103, 'province_id' => 71, 'name' => "KABUPATEN KEPULAUAN SANGIHE",],
            ['id_city' => 7104, 'province_id' => 71, 'name' => "KABUPATEN KEPULAUAN TALAUD",],
            ['id_city' => 7105, 'province_id' => 71, 'name' => "KABUPATEN MINAHASA SELATAN",],
            ['id_city' => 7106, 'province_id' => 71, 'name' => "KABUPATEN MINAHASA UTARA",],
            ['id_city' => 7107, 'province_id' => 71, 'name' => "KABUPATEN BOLAANG MONGONDOW UTARA",],
            ['id_city' => 7108, 'province_id' => 71, 'name' => "KABUPATEN SIAU TAGULANDANG BIARO",],
            ['id_city' => 7109, 'province_id' => 71, 'name' => "KABUPATEN MINAHASA TENGGARA",],
            ['id_city' => 7110, 'province_id' => 71, 'name' => "KABUPATEN BOLAANG MONGONDOW SELATAN",],
            ['id_city' => 7111, 'province_id' => 71, 'name' => "KABUPATEN BOLAANG MONGONDOW TIMUR",],
            ['id_city' => 7171, 'province_id' => 71, 'name' => "KOTA MANADO",],
            ['id_city' => 7172, 'province_id' => 71, 'name' => "KOTA BITUNG",],
            ['id_city' => 7173, 'province_id' => 71, 'name' => "KOTA TOMOHON",],
            ['id_city' => 7174, 'province_id' => 71, 'name' => "KOTA KOTAMOBAGU",],
            ['id_city' => 7201, 'province_id' => 72, 'name' => "KABUPATEN BANGGAI KEPULAUAN",],
            ['id_city' => 7202, 'province_id' => 72, 'name' => "KABUPATEN BANGGAI",],
            ['id_city' => 7203, 'province_id' => 72, 'name' => "KABUPATEN MOROWALI",],
            ['id_city' => 7204, 'province_id' => 72, 'name' => "KABUPATEN POSO",],
            ['id_city' => 7205, 'province_id' => 72, 'name' => "KABUPATEN DONGGALA",],
            ['id_city' => 7206, 'province_id' => 72, 'name' => "KABUPATEN TOLI-TOLI",],
            ['id_city' => 7207, 'province_id' => 72, 'name' => "KABUPATEN BUOL",],
            ['id_city' => 7208, 'province_id' => 72, 'name' => "KABUPATEN PARIGI MOUTONG",],
            ['id_city' => 7209, 'province_id' => 72, 'name' => "KABUPATEN TOJO UNA-UNA",],
            ['id_city' => 7210, 'province_id' => 72, 'name' => "KABUPATEN SIGI",],
            ['id_city' => 7211, 'province_id' => 72, 'name' => "KABUPATEN BANGGAI LAUT",],
            ['id_city' => 7212, 'province_id' => 72, 'name' => "KABUPATEN MOROWALI UTARA",],
            ['id_city' => 7271, 'province_id' => 72, 'name' => "KOTA PALU",],
            ['id_city' => 7301, 'province_id' => 73, 'name' => "KABUPATEN KEPULAUAN SELAYAR",],
            ['id_city' => 7302, 'province_id' => 73, 'name' => "KABUPATEN BULUKUMBA",],
            ['id_city' => 7303, 'province_id' => 73, 'name' => "KABUPATEN BANTAENG",],
            ['id_city' => 7304, 'province_id' => 73, 'name' => "KABUPATEN JENEPONTO",],
            ['id_city' => 7305, 'province_id' => 73, 'name' => "KABUPATEN TAKALAR",],
            ['id_city' => 7306, 'province_id' => 73, 'name' => "KABUPATEN GOWA",],
            ['id_city' => 7307, 'province_id' => 73, 'name' => "KABUPATEN SINJAI",],
            ['id_city' => 7308, 'province_id' => 73, 'name' => "KABUPATEN MAROS",],
            ['id_city' => 7309, 'province_id' => 73, 'name' => "KABUPATEN PANGKAJENE DAN KEPULAUAN",],
            ['id_city' => 7310, 'province_id' => 73, 'name' => "KABUPATEN BARRU",],
            ['id_city' => 7311, 'province_id' => 73, 'name' => "KABUPATEN BONE",],
            ['id_city' => 7312, 'province_id' => 73, 'name' => "KABUPATEN SOPPENG",],
            ['id_city' => 7313, 'province_id' => 73, 'name' => "KABUPATEN WAJO",],
            ['id_city' => 7314, 'province_id' => 73, 'name' => "KABUPATEN SIDENRENG RAPPANG",],
            ['id_city' => 7315, 'province_id' => 73, 'name' => "KABUPATEN PINRANG",],
            ['id_city' => 7316, 'province_id' => 73, 'name' => "KABUPATEN ENREKANG",],
            ['id_city' => 7317, 'province_id' => 73, 'name' => "KABUPATEN LUWU",],
            ['id_city' => 7318, 'province_id' => 73, 'name' => "KABUPATEN TANA TORAJA",],
            ['id_city' => 7322, 'province_id' => 73, 'name' => "KABUPATEN LUWU UTARA",],
            ['id_city' => 7325, 'province_id' => 73, 'name' => "KABUPATEN LUWU TIMUR",],
            ['id_city' => 7326, 'province_id' => 73, 'name' => "KABUPATEN TORAJA UTARA",],
            ['id_city' => 7371, 'province_id' => 73, 'name' => "KOTA MAKASSAR",],
            ['id_city' => 7372, 'province_id' => 73, 'name' => "KOTA PAREPARE",],
            ['id_city' => 7373, 'province_id' => 73, 'name' => "KOTA PALOPO",],
            ['id_city' => 7401, 'province_id' => 74, 'name' => "KABUPATEN BUTON",],
            ['id_city' => 7402, 'province_id' => 74, 'name' => "KABUPATEN MUNA",],
            ['id_city' => 7403, 'province_id' => 74, 'name' => "KABUPATEN KONAWE",],
            ['id_city' => 7404, 'province_id' => 74, 'name' => "KABUPATEN KOLAKA",],
            ['id_city' => 7405, 'province_id' => 74, 'name' => "KABUPATEN KONAWE SELATAN",],
            ['id_city' => 7406, 'province_id' => 74, 'name' => "KABUPATEN BOMBANA",],
            ['id_city' => 7407, 'province_id' => 74, 'name' => "KABUPATEN WAKATOBI",],
            ['id_city' => 7408, 'province_id' => 74, 'name' => "KABUPATEN KOLAKA UTARA",],
            ['id_city' => 7409, 'province_id' => 74, 'name' => "KABUPATEN BUTON UTARA",],
            ['id_city' => 7410, 'province_id' => 74, 'name' => "KABUPATEN KONAWE UTARA",],
            ['id_city' => 7411, 'province_id' => 74, 'name' => "KABUPATEN KOLAKA TIMUR",],
            ['id_city' => 7412, 'province_id' => 74, 'name' => "KABUPATEN KONAWE KEPULAUAN",],
            ['id_city' => 7413, 'province_id' => 74, 'name' => "KABUPATEN MUNA BARAT",],
            ['id_city' => 7414, 'province_id' => 74, 'name' => "KABUPATEN BUTON TENGAH",],
            ['id_city' => 7415, 'province_id' => 74, 'name' => "KABUPATEN BUTON SELATAN",],
            ['id_city' => 7471, 'province_id' => 74, 'name' => "KOTA KENDARI",],
            ['id_city' => 7472, 'province_id' => 74, 'name' => "KOTA BAUBAU",],
            ['id_city' => 7501, 'province_id' => 75, 'name' => "KABUPATEN BOALEMO",],
            ['id_city' => 7502, 'province_id' => 75, 'name' => "KABUPATEN GORONTALO",],
            ['id_city' => 7503, 'province_id' => 75, 'name' => "KABUPATEN POHUWATO",],
            ['id_city' => 7504, 'province_id' => 75, 'name' => "KABUPATEN BONE BOLANGO",],
            ['id_city' => 7505, 'province_id' => 75, 'name' => "KABUPATEN GORONTALO UTARA",],
            ['id_city' => 7571, 'province_id' => 75, 'name' => "KOTA GORONTALO",],
            ['id_city' => 7601, 'province_id' => 76, 'name' => "KABUPATEN MAJENE",],
            ['id_city' => 7602, 'province_id' => 76, 'name' => "KABUPATEN POLEWALI MANDAR",],
            ['id_city' => 7603, 'province_id' => 76, 'name' => "KABUPATEN MAMASA",],
            ['id_city' => 7604, 'province_id' => 76, 'name' => "KABUPATEN MAMUJU",],
            ['id_city' => 7605, 'province_id' => 76, 'name' => "KABUPATEN MAMUJU UTARA",],
            ['id_city' => 7606, 'province_id' => 76, 'name' => "KABUPATEN MAMUJU TENGAH",],
            ['id_city' => 8101, 'province_id' => 81, 'name' => "KABUPATEN MALUKU TENGGARA BARAT",],
            ['id_city' => 8102, 'province_id' => 81, 'name' => "KABUPATEN MALUKU TENGGARA",],
            ['id_city' => 8103, 'province_id' => 81, 'name' => "KABUPATEN MALUKU TENGAH",],
            ['id_city' => 8104, 'province_id' => 81, 'name' => "KABUPATEN BURU",],
            ['id_city' => 8105, 'province_id' => 81, 'name' => "KABUPATEN KEPULAUAN ARU",],
            ['id_city' => 8106, 'province_id' => 81, 'name' => "KABUPATEN SERAM BAGIAN BARAT",],
            ['id_city' => 8107, 'province_id' => 81, 'name' => "KABUPATEN SERAM BAGIAN TIMUR",],
            ['id_city' => 8108, 'province_id' => 81, 'name' => "KABUPATEN MALUKU BARAT DAYA",],
            ['id_city' => 8109, 'province_id' => 81, 'name' => "KABUPATEN BURU SELATAN",],
            ['id_city' => 8171, 'province_id' => 81, 'name' => "KOTA AMBON",],
            ['id_city' => 8172, 'province_id' => 81, 'name' => "KOTA TUAL",],
            ['id_city' => 8201, 'province_id' => 82, 'name' => "KABUPATEN HALMAHERA BARAT",],
            ['id_city' => 8202, 'province_id' => 82, 'name' => "KABUPATEN HALMAHERA TENGAH",],
            ['id_city' => 8203, 'province_id' => 82, 'name' => "KABUPATEN KEPULAUAN SULA",],
            ['id_city' => 8204, 'province_id' => 82, 'name' => "KABUPATEN HALMAHERA SELATAN",],
            ['id_city' => 8205, 'province_id' => 82, 'name' => "KABUPATEN HALMAHERA UTARA",],
            ['id_city' => 8206, 'province_id' => 82, 'name' => "KABUPATEN HALMAHERA TIMUR",],
            ['id_city' => 8207, 'province_id' => 82, 'name' => "KABUPATEN PULAU MOROTAI",],
            ['id_city' => 8208, 'province_id' => 82, 'name' => "KABUPATEN PULAU TALIABU",],
            ['id_city' => 8271, 'province_id' => 82, 'name' => "KOTA TERNATE",],
            ['id_city' => 8272, 'province_id' => 82, 'name' => "KOTA TIDORE KEPULAUAN",],
            ['id_city' => 9101, 'province_id' => 91, 'name' => "KABUPATEN FAKFAK",],
            ['id_city' => 9102, 'province_id' => 91, 'name' => "KABUPATEN KAIMANA",],
            ['id_city' => 9103, 'province_id' => 91, 'name' => "KABUPATEN TELUK WONDAMA",],
            ['id_city' => 9104, 'province_id' => 91, 'name' => "KABUPATEN TELUK BINTUNI",],
            ['id_city' => 9105, 'province_id' => 91, 'name' => "KABUPATEN MANOKWARI",],
            ['id_city' => 9106, 'province_id' => 91, 'name' => "KABUPATEN SORONG SELATAN",],
            ['id_city' => 9107, 'province_id' => 91, 'name' => "KABUPATEN SORONG",],
            ['id_city' => 9108, 'province_id' => 91, 'name' => "KABUPATEN RAJA AMPAT",],
            ['id_city' => 9109, 'province_id' => 91, 'name' => "KABUPATEN TAMBRAUW",],
            ['id_city' => 9110, 'province_id' => 91, 'name' => "KABUPATEN MAYBRAT",],
            ['id_city' => 9111, 'province_id' => 91, 'name' => "KABUPATEN MANOKWARI SELATAN",],
            ['id_city' => 9112, 'province_id' => 91, 'name' => "KABUPATEN PEGUNUNGAN ARFAK",],
            ['id_city' => 9171, 'province_id' => 91, 'name' => "KOTA SORONG",],
            ['id_city' => 9401, 'province_id' => 94, 'name' => "KABUPATEN MERAUKE",],
            ['id_city' => 9402, 'province_id' => 94, 'name' => "KABUPATEN JAYAWIJAYA",],
            ['id_city' => 9403, 'province_id' => 94, 'name' => "KABUPATEN JAYAPURA",],
            ['id_city' => 9404, 'province_id' => 94, 'name' => "KABUPATEN NABIRE",],
            ['id_city' => 9408, 'province_id' => 94, 'name' => "KABUPATEN KEPULAUAN YAPEN",],
            ['id_city' => 9409, 'province_id' => 94, 'name' => "KABUPATEN BIAK NUMFOR",],
            ['id_city' => 9410, 'province_id' => 94, 'name' => "KABUPATEN PANIAI",],
            ['id_city' => 9411, 'province_id' => 94, 'name' => "KABUPATEN PUNCAK JAYA",],
            ['id_city' => 9412, 'province_id' => 94, 'name' => "KABUPATEN MIMIKA",],
            ['id_city' => 9413, 'province_id' => 94, 'name' => "KABUPATEN BOVEN DIGOEL",],
            ['id_city' => 9414, 'province_id' => 94, 'name' => "KABUPATEN MAPPI",],
            ['id_city' => 9415, 'province_id' => 94, 'name' => "KABUPATEN ASMAT",],
            ['id_city' => 9416, 'province_id' => 94, 'name' => "KABUPATEN YAHUKIMO",],
            ['id_city' => 9417, 'province_id' => 94, 'name' => "KABUPATEN PEGUNUNGAN BINTANG",],
            ['id_city' => 9418, 'province_id' => 94, 'name' => "KABUPATEN TOLIKARA",],
            ['id_city' => 9419, 'province_id' => 94, 'name' => "KABUPATEN SARMI",],
            ['id_city' => 9420, 'province_id' => 94, 'name' => "KABUPATEN KEEROM",],
            ['id_city' => 9426, 'province_id' => 94, 'name' => "KABUPATEN WAROPEN",],
            ['id_city' => 9427, 'province_id' => 94, 'name' => "KABUPATEN SUPIORI",],
            ['id_city' => 9428, 'province_id' => 94, 'name' => "KABUPATEN MAMBERAMO RAYA",],
            ['id_city' => 9429, 'province_id' => 94, 'name' => "KABUPATEN NDUGA",],
            ['id_city' => 9430, 'province_id' => 94, 'name' => "KABUPATEN LANNY JAYA",],
            ['id_city' => 9431, 'province_id' => 94, 'name' => "KABUPATEN MAMBERAMO TENGAH",],
            ['id_city' => 9432, 'province_id' => 94, 'name' => "KABUPATEN YALIMO",],
            ['id_city' => 9433, 'province_id' => 94, 'name' => "KABUPATEN PUNCAK",],
            ['id_city' => 9434, 'province_id' => 94, 'name' => "KABUPATEN DOGIYAI",],
            ['id_city' => 9435, 'province_id' => 94, 'name' => "KABUPATEN INTAN JAYA",],
            ['id_city' => 9436, 'province_id' => 94, 'name' => "KABUPATEN DEIYAI",],
            ['id_city' => 9471, 'province_id' => 94, 'name' => "KOTA JAYAPURA",],
        ];
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('regencies')->insert($this->_getData());

        DB::select(DB::raw("
            SELECT SETVAL(
                '\"public\".\"regencies_id_city_seq\"', 
                (SELECT MAX(id_city) FROM regencies),
                false
            )
        "));
    }
}
